export type GalleryImage = {
  id: string;
  src: string;
  thumb: string;
  alt: string;
  title: string;
};

export const galleryImages: GalleryImage[] = [
  {
    id: '1',
    src: '/assets/terminator-images/gallery/Pictures/Cable tray and piping.jpeg',
    thumb: '/assets/terminator-images/gallery/Pictures/Cable tray and piping.jpeg',
    alt: 'Cable tray and piping',
    title: 'Cable tray and piping',
  },
  {
    id: '2',
    src: '/assets/terminator-images/gallery/Pictures/Cable tray and piping1.jpeg',
    thumb: '/assets/terminator-images/gallery/Pictures/Cable tray and piping1.jpeg',
    alt: 'Cable tray and piping',
    title: 'Cable tray and piping',
  },
  {
    id: '3',
    src: '/assets/terminator-images/gallery/Pictures/DB installation.jpeg',
    thumb: '/assets/terminator-images/gallery/Pictures/DB installation.jpeg',
    alt: 'DB installation',
    title: 'DB installation',
  },
  {
    id: '4',
    src: '/assets/terminator-images/gallery/Pictures/Electrical installation.jpeg',
    thumb: '/assets/terminator-images/gallery/Pictures/Electrical installation.jpeg',
    alt: 'Electrical installation',
    title: 'Electrical installation',
  },
  {
    id: '5',
    src: '/assets/terminator-images/gallery/Pictures/Electrical installations.jpeg',
    thumb: '/assets/terminator-images/gallery/Pictures/Electrical installations.jpeg',
    alt: 'Electrical installations',
    title: 'Electrical installations',
  },
  {
    id: '6',
    src: '/assets/terminator-images/gallery/Pictures/EMC works.jpeg',
    thumb: '/assets/terminator-images/gallery/Pictures/EMC works.jpeg',
    alt: 'EMC works',
    title: 'EMC works',
  },
  {
    id: '7',
    src: '/assets/terminator-images/gallery/Pictures/Lighting installations.jpeg',
    thumb: '/assets/terminator-images/gallery/Pictures/Lighting installations.jpeg',
    alt: 'Lighting installations',
    title: 'Lighting installations',
  },
  {
    id: '8',
    src: '/assets/terminator-images/gallery/Pictures/Panel installation.jpeg',
    thumb: '/assets/terminator-images/gallery/Pictures/Panel installation.jpeg',
    alt: 'Panel installation',
    title: 'Panel installation',
  },
  {
    id: '9',
    src: '/assets/terminator-images/gallery/Pictures/Cable tray and Cables/cable installed.jpeg',
    thumb: '/assets/terminator-images/gallery/Pictures/Cable tray and Cables/cable installed.jpeg',
    alt: 'Cable installed',
    title: 'Cable Installed',
  },
  {
    id: '10',
    src: '/assets/terminator-images/gallery/Pictures/Cable tray and Cables/Fabrication of cable tray.jpg',
    thumb: '/assets/terminator-images/gallery/Pictures/Cable tray and Cables/Fabrication of cable tray.jpg',
    alt: 'Fabrication of cable tray',
    title: 'Fabrication of cable tray',
  },
  // {
  //   id: '11',
  //   src: '/assets/terminator-images/gallery/Pictures/Cable tray and Cables/IT termination.jpeg',
  //   thumb: '/assets/terminator-images/gallery/Pictures/Cable tray and Cables/IT termination.jpeg',
  //   alt: 'IT termination',
  //   title: 'IT termination',
  // },
  {
    id: '12',
    src: '/assets/terminator-images/gallery/Pictures/Cable tray and Cables/prj-06-04-bg.jpg',
    thumb: '/assets/terminator-images/gallery/Pictures/Cable tray and Cables/prj-06-04-bg.jpg',
    alt: 'Cable tray and Cables',
    title: 'Cable tray and Cables',
  },
  {
    id: '13',
    src: '/assets/terminator-images/gallery/Pictures/Cable tray and Cables/images (33).jpeg',
    thumb: '/assets/terminator-images/gallery/Pictures/Cable tray and Cables/images (33).jpeg',
    alt: 'Cable tray and Cables',
    title: 'Cable tray and Cables',
  },
  {
    id: '14',
    src: '/assets/terminator-images/gallery/Pictures/Cable tray and Cables/cable tray supports.jpg',
    thumb: '/assets/terminator-images/gallery/Pictures/Cable tray and Cables/cable tray supports.jpg',
    alt: 'cable tray supports',
    title: 'cable tray supports',
  },
  // Customized Test Benches and Panels
  {
    id: '15',
    src: '/assets/terminator-images/gallery/Pictures/Customized Test Benches and Panels/Test bench.jpg',
    thumb: '/assets/terminator-images/gallery/Pictures/Customized Test Benches and Panels/Test bench.jpg',
    alt: 'Test bench',
    title: 'Test bench',
  },
  {
    id: '16',
    src: '/assets/terminator-images/gallery/Pictures/Customized Test Benches and Panels/IMG-20201016-WA0072.jpg',
    thumb: '/assets/terminator-images/gallery/Pictures/Customized Test Benches and Panels/IMG-20201016-WA0072.jpg',
    alt: 'Customized Test Benches and Panels',
    title: 'Customized Test Benches and Panels',
  },
  {
    id: '17',
    src: '/assets/terminator-images/gallery/Pictures/Customized Test Benches and Panels/images13.jpg',
    thumb: '/assets/terminator-images/gallery/Pictures/Customized Test Benches and Panels/images13.jpg',
    alt: 'Customized Test Benches and Panels',
    title: 'Customized Test Benches and Panels',
  },
  // Earthing & LPS
  // {
  //   id: '18',
  //   src: '/assets/terminator-images/gallery/Pictures/Earthing & LPS/20210309_234622.jpg',
  //   thumb: '/assets/terminator-images/gallery/Pictures/Earthing & LPS/20210309_234622.jpg',
  //   alt: 'Earthing & LPS',
  //   title: 'Earthing & LPS',
  // },
  {
    id: '19',
    src: '/assets/terminator-images/gallery/Pictures/Earthing & LPS/20221116_115324.jpg',
    thumb: '/assets/terminator-images/gallery/Pictures/Earthing & LPS/20221116_115324.jpg',
    alt: 'Earthing & LPS',
    title: 'Earthing & LPS',
  },
  // {
  //   id: '20',
  //   src: '/assets/terminator-images/gallery/Pictures/Earthing & LPS/Earthing.jpg',
  //   thumb: '/assets/terminator-images/gallery/Pictures/Earthing & LPS/Earthing.jpg',
  //   alt: 'Earthing',
  //   title: 'Earthing',
  // },
  {
    id: '21',
    src: '/assets/terminator-images/gallery/Pictures/Earthing & LPS/lightning-protection-system-testing-commissioning.gif',
    thumb: '/assets/terminator-images/gallery/Pictures/Earthing & LPS/lightning-protection-system-testing-commissioning.gif',
    alt: 'lightning-protection-system-testing-commissioning',
    title: 'lightning-protection-system-testing-commissioning',
  },
  {
    id: '22',
    src: '/assets/terminator-images/gallery/Pictures/Earthing & LPS/20221116_115845.jpg',
    thumb: '/assets/terminator-images/gallery/Pictures/Earthing & LPS/20221116_115845.jpg',
    alt: 'Earthing & LPS',
    title: 'Earthing & LPS',
  },
  // {
  //   id: '23',
  //   src: '/assets/terminator-images/gallery/Pictures/Earthing & LPS/Faradays Cage.png',
  //   thumb: '/assets/terminator-images/gallery/Pictures/Earthing & LPS/Faradays Cage.png',
  //   alt: 'Faradays Cage',
  //   title: 'Faradays Cage',
  // },
  // Dangerous
  {
    id: '24',
    src: '/assets/terminator-images/gallery/Pictures/Dangerous/5.jpg',
    thumb: '/assets/terminator-images/gallery/Pictures/Dangerous/5.jpg',
    alt: 'Dangerous',
    title: 'Dangerous',
  },
  // Explosion-proof wiring, lights, and power equipment
  {
    id: '25',
    src: '/assets/terminator-images/gallery/Pictures/Explosion-proof wiring, lights, and power equipment/explosion proof lighting 1.jpg',
    thumb: '/assets/terminator-images/gallery/Pictures/Explosion-proof wiring, lights, and power equipment/explosion proof lighting 1.jpg',
    alt: 'explosion proof lighting',
    title: 'explosion proof lighting',
  },
  {
    id: '26',
    src: '/assets/terminator-images/gallery/Pictures/Explosion-proof wiring, lights, and power equipment/Lighting-768x384.jpg',
    thumb: '/assets/terminator-images/gallery/Pictures/Explosion-proof wiring, lights, and power equipment/Lighting-768x384.jpg',
    alt: 'Lighting',
    title: 'Lighting',
  },
  {
    id: '27',
    src: '/assets/terminator-images/gallery/Pictures/Explosion-proof wiring, lights, and power equipment/waking-io-explosion-proof-lighting-16x9-3.jpg',
    thumb: '/assets/terminator-images/gallery/Pictures/Explosion-proof wiring, lights, and power equipment/waking-io-explosion-proof-lighting-16x9-3.jpg',
    alt: 'explosion-proof-lighting',
    title: 'explosion-proof-lighting',
  },
  // Fire Alarm & Extinguishing
  {
    id: '28',
    src: '/assets/terminator-images/gallery/Pictures/Fire Alarm & Extinguishing/Fire-Alarm-Systems.avif',
    thumb: '/assets/terminator-images/gallery/Pictures/Fire Alarm & Extinguishing/Fire-Alarm-Systems.avif',
    alt: 'Fire Alarm Systems',
    title: 'Fire Alarm Systems',
  },
  {
    id: '29',
    src: '/assets/terminator-images/gallery/Pictures/Fire Alarm & Extinguishing/images.jpeg',
    thumb: '/assets/terminator-images/gallery/Pictures/Fire Alarm & Extinguishing/images.jpeg',
    alt: 'Fire Alarm & Extinguishing',
    title: 'Fire Alarm & Extinguishing',
  },
  // HT LT Panels, Sub stations, SwitchGear
  {
    id: '30',
    src: '/assets/terminator-images/gallery/Pictures/HT LT Panels, Sub stations, SwitchGear/20210309_233904.jpg',
    thumb: '/assets/terminator-images/gallery/Pictures/HT LT Panels, Sub stations, SwitchGear/20210309_233904.jpg',
    alt: 'HT LT Panels, Sub stations, SwitchGear',
    title: 'HT LT Panels, Sub stations, SwitchGear',
  },
  {
    id: '31',
    src: '/assets/terminator-images/gallery/Pictures/HT LT Panels, Sub stations, SwitchGear/20210309_233937.jpg',
    thumb: '/assets/terminator-images/gallery/Pictures/HT LT Panels, Sub stations, SwitchGear/20210309_233937.jpg',
    alt: 'HT LT Panels, Sub stations, SwitchGear',
    title: 'HT LT Panels, Sub stations, SwitchGear',
  },
  // {
  //   id: '32',
  //   src: '/assets/terminator-images/gallery/Pictures/HT LT Panels, Sub stations, SwitchGear/20210311_132744.jpg',
  //   thumb: '/assets/terminator-images/gallery/Pictures/HT LT Panels, Sub stations, SwitchGear/20210311_132744.jpg',
  //   alt: 'HT LT Panels, Sub stations, SwitchGear',
  //   title: 'HT LT Panels, Sub stations, SwitchGear',
  // },
  {
    id: '33',
    src: '/assets/terminator-images/gallery/Pictures/HT LT Panels, Sub stations, SwitchGear/20210311_133934.jpg',
    thumb: '/assets/terminator-images/gallery/Pictures/HT LT Panels, Sub stations, SwitchGear/20210311_133934.jpg',
    alt: 'HT LT Panels, Sub stations, SwitchGear',
    title: 'HT LT Panels, Sub stations, SwitchGear',
  },
  {
    id: '34',
    src: '/assets/terminator-images/gallery/Pictures/HT LT Panels, Sub stations, SwitchGear/20210311_133945.jpg',
    thumb: '/assets/terminator-images/gallery/Pictures/HT LT Panels, Sub stations, SwitchGear/20210311_133945.jpg',
    alt: 'HT LT Panels, Sub stations, SwitchGear',
    title: 'HT LT Panels, Sub stations, SwitchGear',
  },
  {
    id: '35',
    src: '/assets/terminator-images/gallery/Pictures/HT LT Panels, Sub stations, SwitchGear/20210311_133957.jpg',
    thumb: '/assets/terminator-images/gallery/Pictures/HT LT Panels, Sub stations, SwitchGear/20210311_133957.jpg',
    alt: 'HT LT Panels, Sub stations, SwitchGear',
    title: 'HT LT Panels, Sub stations, SwitchGear',
  },
  // Indoor and Outdoor Lighting
  // {
  //   id: '36',
  //   src: '/assets/terminator-images/gallery/Pictures/Indoor and Outdoor Lighting/20210311_132919.jpg',
  //   thumb: '/assets/terminator-images/gallery/Pictures/Indoor and Outdoor Lighting/20210311_132919.jpg',
  //   alt: 'Indoor and Outdoor Lighting',
  //   title: 'Indoor and Outdoor Lighting',
  // },
  // {
  //   id: '37',
  //   src: '/assets/terminator-images/gallery/Pictures/Indoor and Outdoor Lighting/20210311_133027.jpg',
  //   thumb: '/assets/terminator-images/gallery/Pictures/Indoor and Outdoor Lighting/20210311_133027.jpg',
  //   alt: 'Indoor and Outdoor Lighting',
  //   title: 'Indoor and Outdoor Lighting',
  // },
  // {
  //   id: '38',
  //   src: '/assets/terminator-images/gallery/Pictures/Indoor and Outdoor Lighting/20210311_133102.jpg',
  //   thumb: '/assets/terminator-images/gallery/Pictures/Indoor and Outdoor Lighting/20210311_133102.jpg',
  //   alt: 'Indoor and Outdoor Lighting',
  //   title: 'Indoor and Outdoor Lighting',
  // },
  // {
  //   id: '39',
  //   src: '/assets/terminator-images/gallery/Pictures/Indoor and Outdoor Lighting/20210311_133127.jpg',
  //   thumb: '/assets/terminator-images/gallery/Pictures/Indoor and Outdoor Lighting/20210311_133127.jpg',
  //   alt: 'Indoor and Outdoor Lighting',
  //   title: 'Indoor and Outdoor Lighting',
  // },
  {
    id: '40',
    src: '/assets/terminator-images/gallery/Pictures/Indoor and Outdoor Lighting/20210311_133216.jpg',
    thumb: '/assets/terminator-images/gallery/Pictures/Indoor and Outdoor Lighting/20210311_133216.jpg',
    alt: 'Indoor and Outdoor Lighting',
    title: 'Indoor and Outdoor Lighting',
  },
  // {
  //   id: '41',
  //   src: '/assets/terminator-images/gallery/Pictures/Indoor and Outdoor Lighting/20210311_133233.jpg',
  //   thumb: '/assets/terminator-images/gallery/Pictures/Indoor and Outdoor Lighting/20210311_133233.jpg',
  //   alt: 'Indoor and Outdoor Lighting',
  //   title: 'Indoor and Outdoor Lighting',
  // },
  // Industrial Commercial Power Distribution
  {
    id: '42',
    src: '/assets/terminator-images/gallery/Pictures/Industrial  Commercial Power Distribution/download (3).jpg',
    thumb: '/assets/terminator-images/gallery/Pictures/Industrial  Commercial Power Distribution/download (3).jpg',
    alt: 'Industrial Commercial Power Distribution',
    title: 'Industrial Commercial Power Distribution',
  },
  {
    id: '43',
    src: '/assets/terminator-images/gallery/Pictures/Industrial  Commercial Power Distribution/electric-4198293_1280-1024x682.jpg',
    thumb: '/assets/terminator-images/gallery/Pictures/Industrial  Commercial Power Distribution/electric-4198293_1280-1024x682.jpg',
    alt: 'Electric Power Distribution',
    title: 'Electric Power Distribution',
  },
  {
    id: '44',
    src: '/assets/terminator-images/gallery/Pictures/Industrial  Commercial Power Distribution/IMG-20180621-WA0141.jpg',
    thumb: '/assets/terminator-images/gallery/Pictures/Industrial  Commercial Power Distribution/IMG-20180621-WA0141.jpg',
    alt: 'Industrial Commercial Power Distribution',
    title: 'Industrial Commercial Power Distribution',
  },
  // Lighting
  // {
  //   id: '45',
  //   src: '/assets/terminator-images/gallery/Pictures/Lighting/20210311_132919.jpg',
  //   thumb: '/assets/terminator-images/gallery/Pictures/Lighting/20210311_132919.jpg',
  //   alt: 'Lighting',
  //   title: 'Lighting',
  // },
  // {
  //   id: '46',
  //   src: '/assets/terminator-images/gallery/Pictures/Lighting/20210311_132919_1.jpg',
  //   thumb: '/assets/terminator-images/gallery/Pictures/Lighting/20210311_132919_1.jpg',
  //   alt: 'Lighting',
  //   title: 'Lighting',
  // },
  {
    id: '47',
    src: '/assets/terminator-images/gallery/Pictures/Lighting/download (18).jpeg',
    thumb: '/assets/terminator-images/gallery/Pictures/Lighting/download (18).jpeg',
    alt: 'Lighting',
    title: 'Lighting',
  },
  {
    id: '48',
    src: '/assets/terminator-images/gallery/Pictures/Lighting/IMG-20180622-WA0236.jpg',
    thumb: '/assets/terminator-images/gallery/Pictures/Lighting/IMG-20180622-WA0236.jpg',
    alt: 'Lighting',
    title: 'Lighting',
  },
  {
    id: '49',
    src: '/assets/terminator-images/gallery/Pictures/Lighting/IMG-20180622-WA0241.jpg',
    thumb: '/assets/terminator-images/gallery/Pictures/Lighting/IMG-20180622-WA0241.jpg',
    alt: 'Lighting',
    title: 'Lighting',
  },
  {
    id: '50',
    src: '/assets/terminator-images/gallery/Pictures/Lighting/IMG-20201016-WA0074.jpg',
    thumb: '/assets/terminator-images/gallery/Pictures/Lighting/IMG-20201016-WA0074.jpg',
    alt: 'Lighting',
    title: 'Lighting',
  },
  // LT panels, Motor Control Centers
  {
    id: '51',
    src: '/assets/terminator-images/gallery/Pictures/LT panels, Motor Control Centers/images (3).jpeg',
    thumb: '/assets/terminator-images/gallery/Pictures/LT panels, Motor Control Centers/images (3).jpeg',
    alt: 'LT panels, Motor Control Centers',
    title: 'LT panels, Motor Control Centers',
  },
  {
    id: '52',
    src: '/assets/terminator-images/gallery/Pictures/LT panels, Motor Control Centers/Motor Control Center.jpg',
    thumb: '/assets/terminator-images/gallery/Pictures/LT panels, Motor Control Centers/Motor Control Center.jpg',
    alt: 'Motor Control Center',
    title: 'Motor Control Center',
  },
  // Mix and Selected
  {
    id: '53',
    src: '/assets/terminator-images/gallery/Pictures/Mix and Selected/100120081534.jpg',
    thumb: '/assets/terminator-images/gallery/Pictures/Mix and Selected/100120081534.jpg',
    alt: 'Mix and Selected',
    title: 'Mix and Selected',
  },
  // {
  //   id: '54',
  //   src: '/assets/terminator-images/gallery/Pictures/Mix and Selected/20210309_234155.jpg',
  //   thumb: '/assets/terminator-images/gallery/Pictures/Mix and Selected/20210309_234155.jpg',
  //   alt: 'Mix and Selected',
  //   title: 'Mix and Selected',
  // },
  // {
  //   id: '55',
  //   src: '/assets/terminator-images/gallery/Pictures/Mix and Selected/20210311_132919.jpg',
  //   thumb: '/assets/terminator-images/gallery/Pictures/Mix and Selected/20210311_132919.jpg',
  //   alt: 'Mix and Selected',
  //   title: 'Mix and Selected',
  // },
  {
    id: '56',
    src: '/assets/terminator-images/gallery/Pictures/Mix and Selected/20210311_133102.jpg',
    thumb: '/assets/terminator-images/gallery/Pictures/Mix and Selected/20210311_133102.jpg',
    alt: 'Mix and Selected',
    title: 'Mix and Selected',
  },
  // {
  //   id: '57',
  //   src: '/assets/terminator-images/gallery/Pictures/Mix and Selected/20210311_133743.jpg',
  //   thumb: '/assets/terminator-images/gallery/Pictures/Mix and Selected/20210311_133743.jpg',
  //   alt: 'Mix and Selected',
  //   title: 'Mix and Selected',
  // },
  {
    id: '58',
    src: '/assets/terminator-images/gallery/Pictures/Mix and Selected/20210311_133758.jpg',
    thumb: '/assets/terminator-images/gallery/Pictures/Mix and Selected/20210311_133758.jpg',
    alt: 'Mix and Selected',
    title: 'Mix and Selected',
  },
  // Power, Distribution Transformers
  {
    id: '59',
    src: '/assets/terminator-images/gallery/Pictures/Power , Distibution Transformers/041120071469.jpg',
    thumb: '/assets/terminator-images/gallery/Pictures/Power , Distibution Transformers/041120071469.jpg',
    alt: 'Power Distribution Transformers',
    title: 'Power Distribution Transformers',
  },
  {
    id: '60',
    src: '/assets/terminator-images/gallery/Pictures/Power , Distibution Transformers/080220081592.jpg',
    thumb: '/assets/terminator-images/gallery/Pictures/Power , Distibution Transformers/080220081592.jpg',
    alt: 'Power Distribution Transformers',
    title: 'Power Distribution Transformers',
  },
  {
    id: '61',
    src: '/assets/terminator-images/gallery/Pictures/Power , Distibution Transformers/080220081593.jpg',
    thumb: '/assets/terminator-images/gallery/Pictures/Power , Distibution Transformers/080220081593.jpg',
    alt: 'Power Distribution Transformers',
    title: 'Power Distribution Transformers',
  },
  {
    id: '62',
    src: '/assets/terminator-images/gallery/Pictures/Power , Distibution Transformers/100120081534.jpg',
    thumb: '/assets/terminator-images/gallery/Pictures/Power , Distibution Transformers/100120081534.jpg',
    alt: 'Power Distribution Transformers',
    title: 'Power Distribution Transformers',
  },
  {
    id: '63',
    src: '/assets/terminator-images/gallery/Pictures/Power , Distibution Transformers/20210309_233801.jpg',
    thumb: '/assets/terminator-images/gallery/Pictures/Power , Distibution Transformers/20210309_233801.jpg',
    alt: 'Power Distribution Transformers',
    title: 'Power Distribution Transformers',
  },

  // PPEs, staff
  //
  // {
  //   id: '66',
  //   src: '/assets/terminator-images/gallery/Pictures/PPEs , staff/20210309_234051.jpg',
  //   thumb: '/assets/terminator-images/gallery/Pictures/PPEs , staff/20210309_234051.jpg',
  //   alt: 'PPEs, staff',
  //   title: 'PPEs, staff',
  // },
  // {
  //   id: '67',
  //   src: '/assets/terminator-images/gallery/Pictures/PPEs , staff/20210309_234155.jpg',
  //   thumb: '/assets/terminator-images/gallery/Pictures/PPEs , staff/20210309_234155.jpg',
  //   alt: 'PPEs, staff',
  //   title: 'PPEs, staff',
  // },

  // {
  //   id: '69',
  //   src: '/assets/terminator-images/gallery/Pictures/PPEs , staff/20210309_234410.jpg',
  //   thumb: '/assets/terminator-images/gallery/Pictures/PPEs , staff/20210309_234410.jpg',
  //   alt: 'PPEs, staff',
  //   title: 'PPEs, staff',
  // },
  // {
  //   id: '70',
  //   src: '/assets/terminator-images/gallery/Pictures/PPEs , staff/20210309_234608.jpg',
  //   thumb: '/assets/terminator-images/gallery/Pictures/PPEs , staff/20210309_234608.jpg',
  //   alt: 'PPEs, staff',
  //   title: 'PPEs, staff',
  // },
  // Radio base Station
  {
    id: '71',
    src: '/assets/terminator-images/gallery/Pictures/Radio base Station/pp-01-Radiobase-Station.jpg',
    thumb: '/assets/terminator-images/gallery/Pictures/Radio base Station/pp-01-Radiobase-Station.jpg',
    alt: 'Radiobase Station',
    title: 'Radiobase Station',
  },
  {
    id: '72',
    src: '/assets/terminator-images/gallery/Pictures/Radio base Station/pp-02-Mob-Radio-station.jpg',
    thumb: '/assets/terminator-images/gallery/Pictures/Radio base Station/pp-02-Mob-Radio-station.jpg',
    alt: 'Mob Radio station',
    title: 'Mob Radio station',
  },
  // Safety Equipmentimages (14).jpg
  // {
  //   id: '73',
  //   src: '/assets/terminator-images/gallery/Pictures/Safety Equipment/20210309_234007.jpg',
  //   thumb: '/assets/terminator-images/gallery/Pictures/Safety Equipment/20210309_234007.jpg',
  //   alt: 'Safety Equipment',
  //   title: 'Safety Equipment',
  // },
  // {
  //   id: '74',
  //   src: '/assets/terminator-images/gallery/Pictures/Safety Equipment/20210309_234329.jpg',
  //   thumb: '/assets/terminator-images/gallery/Pictures/Safety Equipment/20210309_234329.jpg',
  //   alt: 'Safety Equipment',
  //   title: 'Safety Equipment',
  // },
  // {
  //   id: '75',
  //   src: '/assets/terminator-images/gallery/Pictures/Safety Equipment/20210311_152721.jpg',
  //   thumb: '/assets/terminator-images/gallery/Pictures/Safety Equipment/20210311_152721.jpg',
  //   alt: 'Safety Equipment',
  //   title: 'Safety Equipment',
  // },
  // {
  //   id: '76',
  //   src: '/assets/terminator-images/gallery/Pictures/Safety Equipment/20210311_152757.jpg',
  //   thumb: '/assets/terminator-images/gallery/Pictures/Safety Equipment/20210311_152757.jpg',
  //   alt: 'Safety Equipment',
  //   title: 'Safety Equipment',
  // },
  // Solar Power Systems
  {
    id: '77',
    src: '/assets/terminator-images/gallery/Pictures/Solar Power Systems/21762310_1659857140705055_7996155826377693183_o.jpg',
    thumb: '/assets/terminator-images/gallery/Pictures/Solar Power Systems/21762310_1659857140705055_7996155826377693183_o.jpg',
    alt: 'Solar Power Systems',
    title: 'Solar Power Systems',
  },
  {
    id: '78',
    src: '/assets/terminator-images/gallery/Pictures/Solar Power Systems/download (5).jpeg',
    thumb: '/assets/terminator-images/gallery/Pictures/Solar Power Systems/download (5).jpeg',
    alt: 'Solar Power Systems',
    title: 'Solar Power Systems',
  },
  {
    id: '79',
    src: '/assets/terminator-images/gallery/Pictures/Solar Power Systems/idx36.jpg',
    thumb: '/assets/terminator-images/gallery/Pictures/Solar Power Systems/idx36.jpg',
    alt: 'Solar Power Systems',
    title: 'Solar Power Systems',
  },
  {
    id: '80',
    src: '/assets/terminator-images/gallery/Pictures/Solar Power Systems/images (13).jpeg',
    thumb: '/assets/terminator-images/gallery/Pictures/Solar Power Systems/images (13).jpeg',
    alt: 'Solar Power Systems',
    title: 'Solar Power Systems',
  },
  // {
  //   id: '81',
  //   src: '/assets/terminator-images/gallery/Pictures/Solar Power Systems/images (14).jpg',
  //   thumb: '/assets/terminator-images/gallery/Pictures/Solar Power Systems/images (14).jpg',
  //   alt: 'Solar Power Systems',
  //   title: 'Solar Power Systems',
  // },
  {
    id: '82',
    src: '/assets/terminator-images/gallery/Pictures/Solar Power Systems/images (24).jpeg',
    thumb: '/assets/terminator-images/gallery/Pictures/Solar Power Systems/images (24).jpeg',
    alt: 'Solar Power Systems',
    title: 'Solar Power Systems',
  },
  // Street light poles, Masts, and Brackets
  {
    id: '83',
    src: '/assets/terminator-images/gallery/Pictures/Street light poles, Masts, and Brackets/20210311_133922.jpg',
    thumb: '/assets/terminator-images/gallery/Pictures/Street light poles, Masts, and Brackets/20210311_133922.jpg',
    alt: 'Street light poles, Masts, and Brackets',
    title: 'Street light poles, Masts, and Brackets',
  },
  {
    id: '84',
    src: '/assets/terminator-images/gallery/Pictures/Street light poles, Masts, and Brackets/20210311_134557.jpg',
    thumb: '/assets/terminator-images/gallery/Pictures/Street light poles, Masts, and Brackets/20210311_134557.jpg',
    alt: 'Street light poles, Masts, and Brackets',
    title: 'Street light poles, Masts, and Brackets',
  },
  {
    id: '85',
    src: '/assets/terminator-images/gallery/Pictures/Street light poles, Masts, and Brackets/20210311_135028.jpg',
    thumb: '/assets/terminator-images/gallery/Pictures/Street light poles, Masts, and Brackets/20210311_135028.jpg',
    alt: 'Street light poles, Masts, and Brackets',
    title: 'Street light poles, Masts, and Brackets',
  },
  // {
  //   id: '86',
  //   src: '/assets/terminator-images/gallery/Pictures/Street light poles, Masts, and Brackets/20210311_135116.jpg',
  //   thumb: '/assets/terminator-images/gallery/Pictures/Street light poles, Masts, and Brackets/20210311_135116.jpg',
  //   alt: 'Street light poles, Masts, and Brackets',
  //   title: 'Street light poles, Masts, and Brackets',
  // },
  {
    id: '87',
    src: '/assets/terminator-images/gallery/Pictures/Street light poles, Masts, and Brackets/20210311_135239.jpg',
    thumb: '/assets/terminator-images/gallery/Pictures/Street light poles, Masts, and Brackets/20210311_135239.jpg',
    alt: 'Street light poles, Masts, and Brackets',
    title: 'Street light poles, Masts, and Brackets',
  },
  // {
  //   id: '88',
  //   src: '/assets/terminator-images/gallery/Pictures/Street light poles, Masts, and Brackets/20210311_135330.jpg',
  //   thumb: '/assets/terminator-images/gallery/Pictures/Street light poles, Masts, and Brackets/20210311_135330.jpg',
  //   alt: 'Street light poles, Masts, and Brackets',
  //   title: 'Street light poles, Masts, and Brackets',
  // },
  // Telecommunications Towers, Masts, and Poles
  {
    id: '89',
    src: '/assets/terminator-images/gallery/Pictures/Telecommunications Towers, Masts, and Poles/9.jpg',
    thumb: '/assets/terminator-images/gallery/Pictures/Telecommunications Towers, Masts, and Poles/9.jpg',
    alt: 'Telecommunications Towers, Masts, and Poles',
    title: 'Telecommunications Towers, Masts, and Poles',
  },
  {
    id: '90',
    src: '/assets/terminator-images/gallery/Pictures/Telecommunications Towers, Masts, and Poles/download (11).jpeg',
    thumb: '/assets/terminator-images/gallery/Pictures/Telecommunications Towers, Masts, and Poles/download (11).jpeg',
    alt: 'Telecommunications Towers, Masts, and Poles',
    title: 'Telecommunications Towers, Masts, and Poles',
  },
  // {
  //   id: '91',
  //   src: '/assets/terminator-images/gallery/Pictures/Telecommunications Towers, Masts, and Poles/download (12).jpeg',
  //   thumb: '/assets/terminator-images/gallery/Pictures/Telecommunications Towers, Masts, and Poles/download (12).jpeg',
  //   alt: 'Telecommunications Towers, Masts, and Poles',
  //   title: 'Telecommunications Towers, Masts, and Poles',
  // },
  {
    id: '92',
    src: '/assets/terminator-images/gallery/Pictures/Telecommunications Towers, Masts, and Poles/gallery-pict02.jpg',
    thumb: '/assets/terminator-images/gallery/Pictures/Telecommunications Towers, Masts, and Poles/gallery-pict02.jpg',
    alt: 'Telecommunications Towers, Masts, and Poles',
    title: 'Telecommunications Towers, Masts, and Poles',
  },
  {
    id: '93',
    src: '/assets/terminator-images/gallery/Pictures/Telecommunications Towers, Masts, and Poles/images (12).jpeg',
    thumb: '/assets/terminator-images/gallery/Pictures/Telecommunications Towers, Masts, and Poles/images (12).jpeg',
    alt: 'Telecommunications Towers, Masts, and Poles',
    title: 'Telecommunications Towers, Masts, and Poles',
  },
  {
    id: '94',
    src: '/assets/terminator-images/gallery/Pictures/Telecommunications Towers, Masts, and Poles/images (23).jpeg',
    thumb: '/assets/terminator-images/gallery/Pictures/Telecommunications Towers, Masts, and Poles/images (23).jpeg',
    alt: 'Telecommunications Towers, Masts, and Poles',
    title: 'Telecommunications Towers, Masts, and Poles',
  },
  // Transformers and generators
  // {
  //   id: '95',
  //   src: '/assets/terminator-images/gallery/Pictures/Transformers and generators/20210309_234155.jpg',
  //   thumb: '/assets/terminator-images/gallery/Pictures/Transformers and generators/20210309_234155.jpg',
  //   alt: 'Transformers and generators',
  //   title: 'Transformers and generators',
  // },
  // {
  //   id: '96',
  //   src: '/assets/terminator-images/gallery/Pictures/Transformers and generators/20210311_133743.jpg',
  //   thumb: '/assets/terminator-images/gallery/Pictures/Transformers and generators/20210311_133743.jpg',
  //   alt: 'Transformers and generators',
  //   title: 'Transformers and generators',
  // },
  {
    id: '97',
    src: '/assets/terminator-images/gallery/Pictures/Transformers and generators/20210311_133758.jpg',
    thumb: '/assets/terminator-images/gallery/Pictures/Transformers and generators/20210311_133758.jpg',
    alt: 'Transformers and generators',
    title: 'Transformers and generators',
  },
  {
    id: '98',
    src: '/assets/terminator-images/gallery/Pictures/Transformers and generators/generator cat.webp',
    thumb: '/assets/terminator-images/gallery/Pictures/Transformers and generators/generator cat.webp',
    alt: 'generator cat',
    title: 'generator cat',
  },
  {
    id: '99',
    src: '/assets/terminator-images/gallery/Pictures/Transformers and generators/images (12)_1.jpg',
    thumb: '/assets/terminator-images/gallery/Pictures/Transformers and generators/images (12)_1.jpg',
    alt: 'Transformers and generators',
    title: 'Transformers and generators',
  },
  {
    id: '100',
    src: '/assets/terminator-images/gallery/Pictures/Transformers and generators/IMG-20180621-WA0070.jpg',
    thumb: '/assets/terminator-images/gallery/Pictures/Transformers and generators/IMG-20180621-WA0070.jpg',
    alt: 'Transformers and generators',
    title: 'Transformers and generators',
  },
  {
    id: '101',
    src: '/assets/terminator-images/gallery/Pictures/Electrical Installations1.jpeg',
    thumb: '/assets/terminator-images/gallery/Pictures/Electrical Installations1.jpeg',
    alt: 'Electrical installations',
    title: 'Electrical Installations',
  },
  {
    id: '102',
    src: '/assets/terminator-images/gallery/Pictures/Electrical Installations2.jpeg',
    thumb: '/assets/terminator-images/gallery/Pictures/Electrical Installations2.jpeg',
    alt: 'Electrical installations',
    title: 'Electrical Installations',
  },
  {
    id: '103',
    src: '/assets/terminator-images/gallery/Pictures/Electrical Installations3.jpeg',
    thumb: '/assets/terminator-images/gallery/Pictures/Electrical Installations3.jpeg',
    alt: 'Electrical installations',
    title: 'Electrical Installations',
  },
];
