export type GalleryImage = {
  id: string;
  src: string;
  thumb: string;
  alt: string;
  category: 'event' | 'exhibition' | 'general';
  title: string;
};

export const galleryImages: GalleryImage[] = [
  // Events (gallery 1-30)
  {
    id: '1',
    src: '/assets/terminator-images/gallery/gallery (1).jpg',
    thumb: '/assets/terminator-images/gallery/gallery (1).jpg',
    alt: 'Annual Conference 2024 keynote session',
    category: 'event',
    title: 'Annual Conference 2024',
  },
  {
    id: '2',
    src: '/assets/terminator-images/gallery/gallery (2).jpg',
    thumb: '/assets/terminator-images/gallery/gallery (2).jpg',
    alt: 'Networking Gala evening event',
    category: 'event',
    title: 'Networking Gala',
  },
  {
    id: '3',
    src: '/assets/terminator-images/gallery/gallery (3).jpg',
    thumb: '/assets/terminator-images/gallery/gallery (3).jpg',
    alt: 'Professional Workshop training session',
    category: 'event',
    title: 'Professional Workshop',
  },
  {
    id: '4',
    src: '/assets/terminator-images/gallery/gallery (4).jpg',
    thumb: '/assets/terminator-images/gallery/gallery (4).jpg',
    alt: 'Team Building Activity outdoor games',
    category: 'event',
    title: 'Team Building Activity',
  },
  {
    id: '5',
    src: '/assets/terminator-images/gallery/gallery (5).jpg',
    thumb: '/assets/terminator-images/gallery/gallery (5).jpg',
    alt: 'Award Ceremony 2024',
    category: 'event',
    title: 'Award Ceremony',
  },
  {
    id: '6',
    src: '/assets/terminator-images/gallery/gallery (6).jpg',
    thumb: '/assets/terminator-images/gallery/gallery (6).jpg',
    alt: 'Industry Summit panel discussion',
    category: 'event',
    title: 'Industry Summit',
  },
  {
    id: '7',
    src: '/assets/terminator-images/gallery/gallery (7).jpg',
    thumb: '/assets/terminator-images/gallery/gallery (7).jpg',
    alt: 'Leadership Conference speakers',
    category: 'event',
    title: 'Leadership Conference',
  },
  {
    id: '8',
    src: '/assets/terminator-images/gallery/gallery (8).jpg',
    thumb: '/assets/terminator-images/gallery/gallery (8).jpg',
    alt: 'Charity Fundraiser event',
    category: 'event',
    title: 'Charity Fundraiser',
  },
  {
    id: '9',
    src: '/assets/terminator-images/gallery/gallery (9).jpg',
    thumb: '/assets/terminator-images/gallery/gallery (9).jpg',
    alt: 'Startup Pitch Competition',
    category: 'event',
    title: 'Startup Competition',
  },
  {
    id: '10',
    src: '/assets/terminator-images/gallery/gallery (10).jpg',
    thumb: '/assets/terminator-images/gallery/gallery (10).jpg',
    alt: 'Corporate Annual Party',
    category: 'event',
    title: 'Annual Party',
  },
  {
    id: '11',
    src: '/assets/terminator-images/gallery/gallery (11).jpg',
    thumb: '/assets/terminator-images/gallery/gallery (11).jpg',
    alt: 'Technology Seminar presentation',
    category: 'event',
    title: 'Technology Seminar',
  },
  {
    id: '12',
    src: '/assets/terminator-images/gallery/gallery (12).jpg',
    thumb: '/assets/terminator-images/gallery/gallery (12).jpg',
    alt: 'Business Networking Meet',
    category: 'event',
    title: 'Business Networking',
  },
  {
    id: '13',
    src: '/assets/terminator-images/gallery/gallery (13).jpg',
    thumb: '/assets/terminator-images/gallery/gallery (13).jpg',
    alt: 'Product Launch Event',
    category: 'event',
    title: 'Product Launch',
  },
  {
    id: '14',
    src: '/assets/terminator-images/gallery/gallery (14).jpg',
    thumb: '/assets/terminator-images/gallery/gallery (14).jpg',
    alt: 'Marketing Workshop',
    category: 'event',
    title: 'Marketing Workshop',
  },
  {
    id: '15',
    src: '/assets/terminator-images/gallery/gallery (15).jpg',
    thumb: '/assets/terminator-images/gallery/gallery (15).jpg',
    alt: 'Finance Conference',
    category: 'event',
    title: 'Finance Conference',
  },
  {
    id: '16',
    src: '/assets/terminator-images/gallery/gallery (16).jpg',
    thumb: '/assets/terminator-images/gallery/gallery (16).jpg',
    alt: 'HR Training Session',
    category: 'event',
    title: 'HR Training',
  },
  {
    id: '17',
    src: '/assets/terminator-images/gallery/gallery (17).jpg',
    thumb: '/assets/terminator-images/gallery/gallery (17).jpg',
    alt: 'Sales Summit',
    category: 'event',
    title: 'Sales Summit',
  },
  {
    id: '18',
    src: '/assets/terminator-images/gallery/gallery (18).jpg',
    thumb: '/assets/terminator-images/gallery/gallery (18).jpg',
    alt: 'Customer Meetup',
    category: 'event',
    title: 'Customer Meetup',
  },
  {
    id: '19',
    src: '/assets/terminator-images/gallery/gallery (19).jpg',
    thumb: '/assets/terminator-images/gallery/gallery (19).jpg',
    alt: 'Innovation Conference',
    category: 'event',
    title: 'Innovation Conference',
  },
  {
    id: '20',
    src: '/assets/terminator-images/gallery/gallery (20).jpg',
    thumb: '/assets/terminator-images/gallery/gallery (20).jpg',
    alt: 'Corporate Retreat',
    category: 'event',
    title: 'Corporate Retreat',
  },
  {
    id: '21',
    src: '/assets/terminator-images/gallery/gallery (21).jpg',
    thumb: '/assets/terminator-images/gallery/gallery (21).jpg',
    alt: 'Tech Demo Day',
    category: 'event',
    title: 'Tech Demo Day',
  },
  {
    id: '22',
    src: '/assets/terminator-images/gallery/gallery (22).jpg',
    thumb: '/assets/terminator-images/gallery/gallery (22).jpg',
    alt: 'Annual General Meeting',
    category: 'event',
    title: 'AGM 2024',
  },
  {
    id: '23',
    src: '/assets/terminator-images/gallery/gallery (23).jpg',
    thumb: '/assets/terminator-images/gallery/gallery (23).jpg',
    alt: 'Leadership Training',
    category: 'event',
    title: 'Leadership Training',
  },
  {
    id: '24',
    src: '/assets/terminator-images/gallery/gallery (24).jpg',
    thumb: '/assets/terminator-images/gallery/gallery (24).jpg',
    alt: 'Employee Recognition',
    category: 'event',
    title: 'Employee Recognition',
  },
  {
    id: '25',
    src: '/assets/terminator-images/gallery/gallery (25).jpg',
    thumb: '/assets/terminator-images/gallery/gallery (25).jpg',
    alt: 'Industry Awards Night',
    category: 'event',
    title: 'Industry Awards',
  },
  {
    id: '26',
    src: '/assets/terminator-images/gallery/gallery (26).jpg',
    thumb: '/assets/terminator-images/gallery/gallery (26).jpg',
    alt: 'Business Strategy Summit',
    category: 'event',
    title: 'Strategy Summit',
  },
  {
    id: '27',
    src: '/assets/terminator-images/gallery/gallery (27).jpg',
    thumb: '/assets/terminator-images/gallery/gallery (27).jpg',
    alt: 'Digital Marketing Conference',
    category: 'event',
    title: 'Digital Marketing Conference',
  },
  {
    id: '28',
    src: '/assets/terminator-images/gallery/gallery (28).jpg',
    thumb: '/assets/terminator-images/gallery/gallery (28).jpg',
    alt: 'Startup Investor Meet',
    category: 'event',
    title: 'Investor Meet',
  },
  {
    id: '29',
    src: '/assets/terminator-images/gallery/gallery (29).jpg',
    thumb: '/assets/terminator-images/gallery/gallery (29).jpg',
    alt: 'Corporate Sports Day',
    category: 'event',
    title: 'Sports Day',
  },
  {
    id: '30',
    src: '/assets/terminator-images/gallery/gallery (30).jpg',
    thumb: '/assets/terminator-images/gallery/gallery (30).jpg',
    alt: 'Year End Celebration',
    category: 'event',
    title: 'Year End Party',
  },

  // Exhibitions (31-60)
  {
    id: '31',
    src: '/assets/terminator-images/gallery/gallery (31).jpg',
    thumb: '/assets/terminator-images/gallery/gallery (31).jpg',
    alt: 'Modern Art Exhibition installation view',
    category: 'exhibition',
    title: 'Modern Art Exhibition',
  },
  {
    id: '32',
    src: '/assets/terminator-images/gallery/gallery (32).jpg',
    thumb: '/assets/terminator-images/gallery/gallery (32).jpg',
    alt: 'Technology Expo interactive display',
    category: 'exhibition',
    title: 'Technology Expo',
  },
  {
    id: '33',
    src: '/assets/terminator-images/gallery/gallery (33).jpg',
    thumb: '/assets/terminator-images/gallery/gallery (33).jpg',
    alt: 'Design Showcase exhibition area',
    category: 'exhibition',
    title: 'Design Showcase',
  },
  {
    id: '34',
    src: '/assets/terminator-images/gallery/gallery (34).jpg',
    thumb: '/assets/terminator-images/gallery/gallery (34).jpg',
    alt: 'Product Launch exhibition booth',
    category: 'exhibition',
    title: 'Product Launch Expo',
  },
  {
    id: '35',
    src: '/assets/terminator-images/gallery/gallery (35).jpg',
    thumb: '/assets/terminator-images/gallery/gallery (35).jpg',
    alt: 'Automobile Exhibition',
    category: 'exhibition',
    title: 'Auto Expo 2024',
  },
  {
    id: '36',
    src: '/assets/terminator-images/gallery/gallery (36).jpg',
    thumb: '/assets/terminator-images/gallery/gallery (36).jpg',
    alt: 'Fashion Exhibition runway',
    category: 'exhibition',
    title: 'Fashion Week',
  },
  {
    id: '37',
    src: '/assets/terminator-images/gallery/gallery (37).jpg',
    thumb: '/assets/terminator-images/gallery/gallery (37).jpg',
    alt: 'Photography Exhibition',
    category: 'exhibition',
    title: 'Photography Exhibition',
  },
  {
    id: '38',
    src: '/assets/terminator-images/gallery/gallery (38).jpg',
    thumb: '/assets/terminator-images/gallery/gallery (38).jpg',
    alt: 'Architecture Exhibition models',
    category: 'exhibition',
    title: 'Architecture Expo',
  },
  {
    id: '39',
    src: '/assets/terminator-images/gallery/gallery (39).jpg',
    thumb: '/assets/terminator-images/gallery/gallery (39).jpg',
    alt: 'Home Decor Exhibition',
    category: 'exhibition',
    title: 'Home Decor Expo',
  },
  {
    id: '40',
    src: '/assets/terminator-images/gallery/gallery (40).jpg',
    thumb: '/assets/terminator-images/gallery/gallery (40).jpg',
    alt: 'Educational Exhibition',
    category: 'exhibition',
    title: 'Education Fair',
  },
  {
    id: '41',
    src: '/assets/terminator-images/gallery/gallery (41).jpg',
    thumb: '/assets/terminator-images/gallery/gallery (41).jpg',
    alt: 'Healthcare Exhibition',
    category: 'exhibition',
    title: 'Healthcare Expo',
  },
  {
    id: '42',
    src: '/assets/terminator-images/gallery/gallery (42).jpg',
    thumb: '/assets/terminator-images/gallery/gallery (42).jpg',
    alt: 'Green Energy Exhibition',
    category: 'exhibition',
    title: 'Energy Expo',
  },
  {
    id: '43',
    src: '/assets/terminator-images/gallery/gallery (43).jpg',
    thumb: '/assets/terminator-images/gallery/gallery (43).jpg',
    alt: 'Food and Beverage Exhibition',
    category: 'exhibition',
    title: 'Food Expo',
  },
  {
    id: '44',
    src: '/assets/terminator-images/gallery/gallery (44).jpg',
    thumb: '/assets/terminator-images/gallery/gallery (44).jpg',
    alt: 'Art and Craft Exhibition',
    category: 'exhibition',
    title: 'Art & Craft Fair',
  },
  {
    id: '45',
    src: '/assets/terminator-images/gallery/gallery (45).jpg',
    thumb: '/assets/terminator-images/gallery/gallery (45).jpg',
    alt: 'Book Exhibition',
    category: 'exhibition',
    title: 'Book Fair',
  },
  {
    id: '46',
    src: '/assets/terminator-images/gallery/gallery (46).jpg',
    thumb: '/assets/terminator-images/gallery/gallery (46).jpg',
    alt: 'Science Exhibition',
    category: 'exhibition',
    title: 'Science Expo',
  },
  //   {
  //     id: '47',
  //     src: '/assets/terminator-images/gallery/gallery (47).jpg',
  //     thumb: '/assets/terminator-images/gallery/gallery (47).jpg',
  //     alt: 'Digital Art Exhibition',
  //     category: 'exhibition',
  //     title: 'Digital Art Expo',
  //   },
  //   {
  //     id: '48',
  //     src: '/assets/terminator-images/gallery/gallery (48).jpg',
  //     thumb: '/assets/terminator-images/gallery/gallery (48).jpg',
  //     alt: 'Industrial Exhibition',
  //     category: 'exhibition',
  //     title: 'Industrial Expo',
  //   },
  //   {
  //     id: '49',
  //     src: '/assets/terminator-images/gallery/gallery (49).jpg',
  //     thumb: '/assets/terminator-images/gallery/gallery (49).jpg',
  //     alt: 'Jewelry Exhibition',
  //     category: 'exhibition',
  //     title: 'Jewelry Expo',
  //   },
  //   {
  //     id: '50',
  //     src: '/assets/terminator-images/gallery/gallery (50).jpg',
  //     thumb: '/assets/terminator-images/gallery/gallery (50).jpg',
  //     alt: 'Real Estate Exhibition',
  //     category: 'exhibition',
  //     title: 'Property Expo',
  //   },
  //   {
  //     id: '51',
  //     src: '/assets/terminator-images/gallery/gallery (51).jpg',
  //     thumb: '/assets/terminator-images/gallery/gallery (51).jpg',
  //     alt: 'Travel and Tourism Exhibition',
  //     category: 'exhibition',
  //     title: 'Travel Expo',
  //   },
  //   {
  //     id: '52',
  //     src: '/assets/terminator-images/gallery/gallery (52).jpg',
  //     thumb: '/assets/terminator-images/gallery/gallery (52).jpg',
  //     alt: 'Sports Equipment Exhibition',
  //     category: 'exhibition',
  //     title: 'Sports Expo',
  //   },
  //   {
  //     id: '53',
  //     src: '/assets/terminator-images/gallery/gallery (53).jpg',
  //     thumb: '/assets/terminator-images/gallery/gallery (53).jpg',
  //     alt: 'Music Instruments Exhibition',
  //     category: 'exhibition',
  //     title: 'Music Expo',
  //   },
  //   {
  //     id: '54',
  //     src: '/assets/terminator-images/gallery/gallery (54).jpg',
  //     thumb: '/assets/terminator-images/gallery/gallery (54).jpg',
  //     alt: 'Film and Media Exhibition',
  //     category: 'exhibition',
  //     title: 'Media Expo',
  //   },
  //   {
  //     id: '55',
  //     src: '/assets/terminator-images/gallery/gallery (55).jpg',
  //     thumb: '/assets/terminator-images/gallery/gallery (55).jpg',
  //     alt: 'Agriculture Exhibition',
  //     category: 'exhibition',
  //     title: 'Agriculture Expo',
  //   },
  //   {
  //     id: '56',
  //     src: '/assets/terminator-images/gallery/gallery (56).jpg',
  //     thumb: '/assets/terminator-images/gallery/gallery (56).jpg',
  //     alt: 'Textile Exhibition',
  //     category: 'exhibition',
  //     title: 'Textile Expo',
  //   },
  //   {
  //     id: '57',
  //     src: '/assets/terminator-images/gallery/gallery (57).jpg',
  //     thumb: '/assets/terminator-images/gallery/gallery (57).jpg',
  //     alt: 'Renewable Energy Exhibition',
  //     category: 'exhibition',
  //     title: 'Renewable Energy Expo',
  //   },
  //   {
  //     id: '58',
  //     src: '/assets/terminator-images/gallery/gallery (58).jpg',
  //     thumb: '/assets/terminator-images/gallery/gallery (58).jpg',
  //     alt: 'Handicrafts Exhibition',
  //     category: 'exhibition',
  //     title: 'Handicrafts Fair',
  //   },
  //   {
  //     id: '59',
  //     src: '/assets/terminator-images/gallery/gallery (59).jpg',
  //     thumb: '/assets/terminator-images/gallery/gallery (59).jpg',
  //     alt: 'Corporate Exhibition',
  //     category: 'exhibition',
  //     title: 'Corporate Expo',
  //   },
  //   {
  //     id: '60',
  //     src: '/assets/terminator-images/gallery/gallery (60).jpg',
  //     thumb: '/assets/terminator-images/gallery/gallery (60).jpg',
  //     alt: 'Innovation Exhibition',
  //     category: 'exhibition',
  //     title: 'Innovation Expo',
  //   },

//   // General Gallery (61-87)
//   {
//     id: '61',
//     src: '/assets/terminator-images/gallery/gallery (61).jpg',
//     thumb: '/assets/terminator-images/gallery/gallery (61).jpg',
//     alt: 'Modern Office interior design',
//     category: 'general',
//     title: 'Modern Office',
//   },
//   {
//     id: '62',
//     src: '/assets/terminator-images/gallery/gallery (62).jpg',
//     thumb: '/assets/terminator-images/gallery/gallery (62).jpg',
//     alt: 'Conference Room setup',
//     category: 'general',
//     title: 'Conference Room',
//   },
//   {
//     id: '63',
//     src: '/assets/terminator-images/gallery/gallery (63).jpg',
//     thumb: '/assets/terminator-images/gallery/gallery (63).jpg',
//     alt: 'Creative workspace environment',
//     category: 'general',
//     title: 'Creative Space',
//   },
//   {
//     id: '64',
//     src: '/assets/terminator-images/gallery/gallery (64).jpg',
//     thumb: '/assets/terminator-images/gallery/gallery (64).jpg',
//     alt: 'Main Hall architecture',
//     category: 'general',
//     title: 'Main Hall',
//   },
//   {
//     id: '65',
//     src: '/assets/terminator-images/gallery/gallery (65).jpg',
//     thumb: '/assets/terminator-images/gallery/gallery (65).jpg',
//     alt: 'Reception Area',
//     category: 'general',
//     title: 'Reception',
//   },
//   {
//     id: '66',
//     src: '/assets/terminator-images/gallery/gallery (66).jpg',
//     thumb: '/assets/terminator-images/gallery/gallery (66).jpg',
//     alt: 'Cafeteria and Lounge',
//     category: 'general',
//     title: 'Cafeteria',
//   },
//   {
//     id: '67',
//     src: '/assets/terminator-images/gallery/gallery (67).jpg',
//     thumb: '/assets/terminator-images/gallery/gallery (67).jpg',
//     alt: 'Auditorium seating',
//     category: 'general',
//     title: 'Auditorium',
//   },
//   {
//     id: '68',
//     src: '/assets/terminator-images/gallery/gallery (68).jpg',
//     thumb: '/assets/terminator-images/gallery/gallery (68).jpg',
//     alt: 'Library interior',
//     category: 'general',
//     title: 'Library',
//   },
//   {
//     id: '69',
//     src: '/assets/terminator-images/gallery/gallery (69).jpg',
//     thumb: '/assets/terminator-images/gallery/gallery (69).jpg',
//     alt: 'Outdoor Garden area',
//     category: 'general',
//     title: 'Garden',
//   },
//   {
//     id: '70',
//     src: '/assets/terminator-images/gallery/gallery (70).jpg',
//     thumb: '/assets/terminator-images/gallery/gallery (70).jpg',
//     alt: 'Meeting Room',
//     category: 'general',
//     title: 'Meeting Room',
//   },
//   {
//     id: '71',
//     src: '/assets/terminator-images/gallery/gallery (71).jpg',
//     thumb: '/assets/terminator-images/gallery/gallery (71).jpg',
//     alt: 'Training Center',
//     category: 'general',
//     title: 'Training Center',
//   },
//   {
//     id: '72',
//     src: '/assets/terminator-images/gallery/gallery (72).jpg',
//     thumb: '/assets/terminator-images/gallery/gallery (72).jpg',
//     alt: 'Executive Office',
//     category: 'general',
//     title: 'Executive Office',
//   },
//   {
//     id: '73',
//     src: '/assets/terminator-images/gallery/gallery (73).jpg',
//     thumb: '/assets/terminator-images/gallery/gallery (73).jpg',
//     alt: 'Collaboration Space',
//     category: 'general',
//     title: 'Collaboration Space',
//   },
//   {
//     id: '74',
//     src: '/assets/terminator-images/gallery/gallery (74).jpg',
//     thumb: '/assets/terminator-images/gallery/gallery (74).jpg',
//     alt: 'Wellness Center',
//     category: 'general',
//     title: 'Wellness Center',
//   },
//   {
//     id: '75',
//     src: '/assets/terminator-images/gallery/gallery (75).jpg',
//     thumb: '/assets/terminator-images/gallery/gallery (75).jpg',
//     alt: 'Parking Facility',
//     category: 'general',
//     title: 'Parking Area',
//   },
//   {
//     id: '76',
//     src: '/assets/terminator-images/gallery/gallery (76).jpg',
//     thumb: '/assets/terminator-images/gallery/gallery (76).jpg',
//     alt: 'Lobby entrance',
//     category: 'general',
//     title: 'Main Lobby',
//   },
//   {
//     id: '77',
//     src: '/assets/terminator-images/gallery/gallery (77).jpg',
//     thumb: '/assets/terminator-images/gallery/gallery (77).jpg',
//     alt: 'Restaurant area',
//     category: 'general',
//     title: 'Restaurant',
//   },
//   {
//     id: '78',
//     src: '/assets/terminator-images/gallery/gallery (78).jpg',
//     thumb: '/assets/terminator-images/gallery/gallery (78).jpg',
//     alt: 'Swimming Pool',
//     category: 'general',
//     title: 'Swimming Pool',
//   },
//   {
//     id: '79',
//     src: '/assets/terminator-images/gallery/gallery (79).jpg',
//     thumb: '/assets/terminator-images/gallery/gallery (79).jpg',
//     alt: 'Gymnasium',
//     category: 'general',
//     title: 'Gym',
//   },
//   {
//     id: '80',
//     src: '/assets/terminator-images/gallery/gallery (80).jpg',
//     thumb: '/assets/terminator-images/gallery/gallery (80).jpg',
//     alt: 'Play Area',
//     category: 'general',
//     title: 'Play Area',
//   },
//   {
//     id: '81',
//     src: '/assets/terminator-images/gallery/gallery (81).jpg',
//     thumb: '/assets/terminator-images/gallery/gallery (81).jpg',
//     alt: 'Meditation Room',
//     category: 'general',
//     title: 'Meditation Room',
//   },
//   {
//     id: '82',
//     src: '/assets/terminator-images/gallery/gallery (82).jpg',
//     thumb: '/assets/terminator-images/gallery/gallery (82).jpg',
//     alt: 'Art Gallery',
//     category: 'general',
//     title: 'Art Gallery',
//   },
//   {
//     id: '83',
//     src: '/assets/terminator-images/gallery/gallery (83).jpg',
//     thumb: '/assets/terminator-images/gallery/gallery (83).jpg',
//     alt: 'Roof Top View',
//     category: 'general',
//     title: 'Rooftop',
//   },
//   {
//     id: '84',
//     src: '/assets/terminator-images/gallery/gallery (84).jpg',
//     thumb: '/assets/terminator-images/gallery/gallery (84).jpg',
//     alt: 'Night View',
//     category: 'general',
//     title: 'Night View',
//   },
//   {
//     id: '85',
//     src: '/assets/terminator-images/gallery/gallery (85).jpg',
//     thumb: '/assets/terminator-images/gallery/gallery (85).jpg',
//     alt: 'Architectural Detail',
//     category: 'general',
//     title: 'Architecture',
//   },
//   {
//     id: '86',
//     src: '/assets/terminator-images/gallery/gallery (86).jpg',
//     thumb: '/assets/terminator-images/gallery/gallery (86).jpg',
//     alt: 'Interior Design',
//     category: 'general',
//     title: 'Interior Design',
//   },
//   {
//     id: '87',
//     src: '/assets/terminator-images/gallery/gallery (87).jpg',
//     thumb: '/assets/terminator-images/gallery/gallery (87).jpg',
//     alt: 'Panoramic View',
//     category: 'general',
//     title: 'Panoramic View',
//   },
];
