export type PortfolioItem = {
  id: string;
  src: string;
  thumb: string;
  alt: string;
  category: 'industrial' | 'commercial' | 'residential' | 'infrastructure';
  title: string;
  description?: string;
  year?: string;
  client?: string;
  location?: string;
};

export const portfolioItems: PortfolioItem[] = [
  {
    id: '1',
    src: '/assets/terminator-images/portfolio/img1.jpg',
    thumb: '/assets/terminator-images/portfolio/img1.jpg',
    alt: 'Industrial Power Plant Installation',
    category: 'industrial',
    title: 'Power Generation Plant',
    description: '5MW Diesel Power Plant installation and commissioning',
    year: '2023',
    client: 'Textile Manufacturing Co.',
    location: 'Karachi, Pakistan',
  },
  {
    id: '2',
    src: '/assets/terminator-images/portfolio/img2.jpg',
    thumb: '/assets/terminator-images/portfolio/img2.jpg',
    alt: 'Industrial Electrification',
    category: 'industrial',
    title: 'Factory Electrification',
    description: 'Complete electrical system for manufacturing unit',
    year: '2023',
    client: 'Steel Mills Ltd',
    location: 'Lahore, Pakistan',
  },
  {
    id: '3',
    src: '/assets/terminator-images/portfolio/img3.jpg',
    thumb: '/assets/terminator-images/portfolio/img3.jpg',
    alt: 'Control Panel Installation',
    category: 'industrial',
    title: 'Control Room Setup',
    description: 'LT Panels and Motor Control Centers installation',
    year: '2022',
    client: 'Chemical Industries',
    location: 'Faisalabad, Pakistan',
  },
  {
    id: '4',
    src: '/assets/terminator-images/portfolio/img4.jpg',
    thumb: '/assets/terminator-images/portfolio/img4.jpg',
    alt: 'Industrial Lighting',
    category: 'industrial',
    title: 'Factory Lighting System',
    description: 'High-bay lighting installation for warehouse',
    year: '2022',
    client: 'Food Processing Plant',
    location: 'Islamabad, Pakistan',
  },

  // Commercial Projects
  {
    id: '5',
    src: '/assets/terminator-images/portfolio/img5.jpg',
    thumb: '/assets/terminator-images/portfolio/img5.jpg',
    alt: 'Shopping Mall Electrical',
    category: 'commercial',
    title: 'Shopping Mall Wiring',
    description: 'Complete electrical wiring and distribution',
    year: '2024',
    client: 'Mega Mall',
    location: 'Karachi, Pakistan',
  },
  {
    id: '6',
    src: '/assets/terminator-images/portfolio/img6.jpg',
    thumb: '/assets/terminator-images/portfolio/img6.jpg',
    alt: 'Office Building Electrification',
    category: 'commercial',
    title: 'Corporate Office Setup',
    description: 'Office building electrification and backup systems',
    year: '2023',
    client: 'Tech Solutions Inc.',
    location: 'Karachi, Pakistan',
  },
  {
    id: '7',
    src: '/assets/terminator-images/portfolio/img7.jpg',
    thumb: '/assets/terminator-images/portfolio/img7.jpg',
    alt: 'Hotel Electrical Systems',
    category: 'commercial',
    title: '5-Star Hotel Wiring',
    description: 'Complete electrical systems for luxury hotel',
    year: '2023',
    client: 'Grand Hotel',
    location: 'Lahore, Pakistan',
  },
  {
    id: '8',
    src: '/assets/terminator-images/portfolio/img8.jpg',
    thumb: '/assets/terminator-images/portfolio/img8.jpg',
    alt: 'Hospital Electrical',
    category: 'commercial',
    title: 'Hospital Power Backup',
    description: 'Emergency power systems for hospital',
    year: '2022',
    client: 'City Hospital',
    location: 'Islamabad, Pakistan',
  },

  // Residential Projects
  {
    id: '9',
    src: '/assets/terminator-images/portfolio/img9.jpg',
    thumb: '/assets/terminator-images/portfolio/img9.jpg',
    alt: 'Residential Building Wiring',
    category: 'residential',
    title: 'Apartment Complex',
    description: 'Complete electrical wiring for residential complex',
    year: '2024',
    client: 'Garden Apartments',
    location: 'Karachi, Pakistan',
  },
  {
    id: '10',
    src: '/assets/terminator-images/portfolio/img10.jpg',
    thumb: '/assets/terminator-images/portfolio/img10.jpg',
    alt: 'Villa Electrical Setup',
    category: 'residential',
    title: 'Luxury Villa Wiring',
    description: 'Smart home electrical systems installation',
    year: '2023',
    client: 'Private Villa',
    location: 'Karachi, Pakistan',
  },
  {
    id: '11',
    src: '/assets/terminator-images/portfolio/img11.jpg',
    thumb: '/assets/terminator-images/portfolio/img11.jpg',
    alt: 'House Renovation',
    category: 'residential',
    title: 'House Renovation',
    description: 'Complete electrical renovation',
    year: '2022',
    client: 'Residential Property',
    location: 'Lahore, Pakistan',
  },
  {
    id: '12',
    src: '/assets/terminator-images/portfolio/img12.jpg',
    thumb: '/assets/terminator-images/portfolio/img12.jpg',
    alt: 'Security Lighting',
    category: 'residential',
    title: 'Residential Security Lighting',
    description: 'Outdoor security lighting system',
    year: '2022',
    client: 'Housing Society',
    location: 'Islamabad, Pakistan',
  },

  // Infrastructure Projects
  {
    id: '13',
    src: '/assets/terminator-images/portfolio/img13.jpg',
    thumb: '/assets/terminator-images/portfolio/img13.jpg',
    alt: 'Street Lighting',
    category: 'infrastructure',
    title: 'City Street Lighting',
    description: 'Street light poles installation',
    year: '2024',
    client: 'Municipal Corporation',
    location: 'Karachi, Pakistan',
  },
  {
    id: '14',
    src: '/assets/terminator-images/portfolio/img14.jpeg',
    thumb: '/assets/terminator-images/portfolio/img14.jpeg',
    alt: 'Transmission Lines',
    category: 'infrastructure',
    title: 'Transmission Lines',
    description: 'HV Transmission line installation',
    year: '2023',
    client: 'Power Distribution Company',
    location: 'Punjab, Pakistan',
  },
  {
    id: '15',
    src: '/assets/terminator-images/portfolio/img15.jpeg',
    thumb: '/assets/terminator-images/portfolio/img15.jpeg',
    alt: 'Telecom Tower',
    category: 'infrastructure',
    title: 'Telecom Tower Installation',
    description: 'Telecommunications tower erection',
    year: '2023',
    client: 'Mobile Network Operator',
    location: 'Sindh, Pakistan',
  },
  {
    id: '16',
    src: '/assets/terminator-images/portfolio/img16.jpeg',
    thumb: '/assets/terminator-images/portfolio/img16.jpeg',
    alt: 'Substation Construction',
    category: 'infrastructure',
    title: 'Grid Substation',
    description: '11kV substation construction',
    year: '2022',
    client: 'Power Utility Company',
    location: 'Karachi, Pakistan',
  },
];

export const portfolioCategories = [
  { id: 'all', label: 'All Projects', value: 'all' },
  { id: 'industrial', label: 'Industrial', value: 'industrial' },
  { id: 'commercial', label: 'Commercial', value: 'commercial' },
  { id: 'residential', label: 'Residential', value: 'residential' },
  { id: 'infrastructure', label: 'Infrastructure', value: 'infrastructure' },
];
